# Generated by Django 4.0.1 on 2024-09-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_contact_email_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image1', models.ImageField(upload_to='image1/')),
                ('image2', models.ImageField(upload_to='image2/')),
                ('image3', models.ImageField(upload_to='image3/')),
                ('image4', models.ImageField(upload_to='image4/')),
                ('image5', models.ImageField(upload_to='image5/')),
                ('image6', models.ImageField(upload_to='image6/')),
            ],
        ),
    ]
