# Generated by Django 4.0.1 on 2024-09-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('espace', models.CharField(choices=[('Fumeur', 'Fumeur'), ('Non Fumeur', 'Non Fumeur'), ('Sans Avis', 'Sans Avis')], max_length=150)),
                ('messgae', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
    ]
