# Generated by Django 4.0.1 on 2024-09-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_reservation_alter_gallery_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='messgae',
            new_name='message',
        ),
    ]
